#!/bin/bash
tdate=`date +"%m-%d-%Y"`
ydate=`date +"%Y%m%d" -d "-2 day"`
echo "$ydate"

sleep 5


hive -e "select */ from logoud.ims limit 5" > teste.xls;
rs=$?

        if [ "$rs" = "0" ]; then
echo"job success"
        else
echo "Job Failed." | mail -s "Job Fail Notification" ogoud@walmartlabs.com
fi

echo "Mail Sent"

****************
if [ "$?" -ne "0" ] or use this ( var1=$? if [ "$var1" = "0" ] )
then
    <send me email however you want to about failure>
else
    <send me email about success how ever you want> 
fi

****************
The subject of the email can be specified with a -s and a list of address with -t. You can write the text on your own with the echo command:

echo "This will go into the body of the mail." | mail -s "Hello world" you@youremail.com
or get it from other files too:

mail -s "Hello world" you@youremailid.com < /home/calvin/application.log
mail doesn't support the sending of attachments, but Mutt does:

echo "Sending an attachment." | mutt -a file.zip -s "attachment" target@email.com
Note that Mutt's much more complete than mail. You can find better explanation here

************************
UPDATE
  table_name
SET
  column = 'value';
That will only "insert" data into a single column while leaving everything else undisturbed.


Create table with CSV files
****************************
	create table if not exists Ogoud.datetest ( date string, test string);

Load data from CSV
****************************
load data local inpath '/home/ogoud/setup.csv' into table ogoud.setup;

	
Inserting from a query with updated timestamp
**********************************************	
	 insert into table imsvsing  select ims.wmweek, ims.gtin,ims.vendorID, ims.ubergm, ing.item_id, ing.si_item_num, ing.primary_si,
	 ing.is_orderable, ing.sims_response,ing.first_ingested_on,ing.setup_completed_on, ing.last_state,	 ing.last_status, FROM_UNIXTIME(UNIX_TIMESTAMP(),'yyyy-MM-dd') 
	 datelocal from ogoud.ims822 ims left join msaxen1.SUPPLIER_ITEM_SETUP_DATA ing on ims.gtin=ing.gtin and ims.vendorID=ing.vendor_id;

Create table from a query and partitioning
*******************************************	 
	create table imsvsing (wmweek string, gtin string,vendorID string, ubergm string, item_id string, si_item_num string, primary_si string, is_orderable string,
	sims_response string,first_ingested_on string,setup_completed_on string, last_state string, last_status string) PARTITIONED BY (date_id date) STORED AS ORC;
	



